# Generated by Django 4.1.2 on 2023-05-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
